// Generated by dev.kolektiv.keel.typegen.Typegen. Do not edit.

export interface Viewer {
  id: string
  username: string
  displayName: string
  timeZone: string
  accent: string
  admin: boolean
  email: string | null
  emailVerified: boolean
  avatarUrl: string | null
  publicAccess: string
}

export interface CalendarSummary {
  id: string
  displayName: string
  description: string | null
  timeZone: string
  color: string
  hidden: boolean
  ownerName: string
  ownerAvatarUrl: string | null
  permission: string
  publicLinkEnabled: boolean
  publicLinkToken: string | null
  requestsEnabled: boolean
  accessMode: string
  effectiveAccessMode: string
  organizationId: string | null
  organizationName: string | null
  organizationSlug: string | null
  teamId: string | null
  teamName: string | null
  connectionId: string | null
  syncDirection: string | null
  syncStatus: string | null
  syncError: string | null
}

export interface AdminUserSummary {
  id: string
  username: string
  displayName: string
  timeZone: string
  admin: boolean
  calendars: CalendarSummary[]
  email: string | null
  emailVerified: boolean
  superadmin: boolean
  storageBytes: number
  quotaBytes: number | null
  groups: string[]
}

export interface HolidayCatalogItem {
  id: string
  name: string
  region: string
}

export interface CustomHolidaySummary {
  id: string
  title: string
  month: number
  day: number
}

export interface GroupSummary {
  id: string
  name: string
  isSystem: boolean
  storageQuotaBytes: number | null
  memberCount: number
}

export interface AdminCalendarSummary {
  id: string
  displayName: string
  ownerUsername: string
  eventCount: number
  publicLinkEnabled: boolean
}

export interface AdminPage {
  viewer: Viewer
  registrationOpen: boolean
  emailVerificationPolicy: string
  publicAccess: string
  users: AdminUserSummary[]
  showHolidays: boolean
  holidayCatalog: HolidayCatalogItem[]
  subscribedHolidayIds: string[]
  customHolidays: CustomHolidaySummary[]
  groups: GroupSummary[]
  calendars: AdminCalendarSummary[]
  oauthRegistration: boolean
}

export interface DirectoryOrgSummary {
  id: string
  slug: string
  displayName: string
  description: string | null
  avatarUrl: string | null
  memberCount: number
  viewerRole: string | null
}

export interface DirectoryUserSummary {
  userId: string
  username: string
  displayName: string
  avatarUrl: string | null
}

export interface DirectoryCalendarSummary {
  id: string
  displayName: string
  token: string
  ownerName: string
  ownerUsername: string | null
  organizationName: string | null
  color: string
}

export interface PublicDirectoryPage {
  viewer: Viewer | null
  publicAccess: string
  orgs: DirectoryOrgSummary[]
  users: DirectoryUserSummary[]
  calendars: DirectoryCalendarSummary[]
}

export interface RecurrenceSummary {
  frequency: string
  interval: number
  until: string | null
  count: number | null
}

export interface EventSummary {
  id: string
  calendarId: string
  title: string
  description: string | null
  location: string | null
  url: string | null
  start: string
  end: string
  allDay: boolean
  timeZone: string | null
  status: string
  recurrence: RecurrenceSummary | null
  etag: string
  openRsvp: boolean
  rsvpStatus: string | null
  attendeeCount: number
}

export interface FriendSummary {
  userId: string
  username: string
  displayName: string
  avatarUrl: string | null
}

export interface FriendRequestSummary {
  id: string
  user: FriendSummary
  createdAt: string
}

export interface TeamSummary {
  id: string
  organizationId: string
  slug: string
  name: string
  memberCount: number
  viewerTeamRole: string | null
  canManageGrants: boolean
}

export interface HomePage {
  viewer: Viewer | null
  viewingUser: Viewer | null
  readOnly: boolean
  registrationOpen: boolean
  timeZone: string
  view: string
  date: string
  previousDate: string
  nextDate: string
  weekStart: string
  gridStart: string
  gridEnd: string
  label: string
  today: string
  now: string
  calendars: CalendarSummary[]
  events: EventSummary[]
  showHolidays: boolean
  holidayCatalog: HolidayCatalogItem[]
  subscribedHolidayIds: string[]
  customHolidays: CustomHolidaySummary[]
  friends: FriendSummary[]
  friendRequests: FriendRequestSummary[]
  teams: TeamSummary[]
}

export interface LoginPage {
  viewer: Viewer | null
}

export interface NotFoundPage {
  path: string
  title: string
}

export interface NotificationSummary {
  id: string
  kind: string
  title: string
  body: string | null
  href: string | null
  read: boolean
  createdAt: string
}

export interface NotificationsPage {
  viewer: Viewer
  notifications: NotificationSummary[]
  unreadCount: number
}

export interface OrganizationSummary {
  id: string
  slug: string
  displayName: string
  description: string | null
  visibility: string
  avatarUrl: string | null
  role: string | null
  memberCount: number
}

export interface OrganizationInvitationSummary {
  id: string
  email: string | null
  userId: string | null
  username: string | null
  displayName: string | null
  role: string
  status: string
  createdAt: string
  expiresAt: string
}

export interface OrganizationMemberSummary {
  userId: string
  username: string
  displayName: string
  avatarUrl: string | null
  role: string
  isSelf: boolean
}

export interface OrganizationProfilePage {
  org: OrganizationSummary
  viewer: Viewer | null
  viewerRole: string | null
  pendingInvitation: OrganizationInvitationSummary | null
  inviteToken: string | null
  members: OrganizationMemberSummary[]
  calendars: CalendarSummary[]
  canManageSettings: boolean
}

export interface OrganizationTeamMemberSummary {
  userId: string
  username: string
  displayName: string
  avatarUrl: string | null
  role: string
  isSelf: boolean
}

export interface OrganizationTeamCalendarSummary {
  calendarId: string
  displayName: string
  color: string
  permission: string
}

export interface OrganizationTeamSummary {
  id: string
  organizationId: string
  slug: string
  name: string
  description: string | null
  isDefault: boolean
  memberCount: number
  viewerRole: string | null
  canManageMembers: boolean
  canManageGrants: boolean
  canDelete: boolean
  members: OrganizationTeamMemberSummary[]
  grants: OrganizationTeamCalendarSummary[]
}

export interface CalendarOptionSummary {
  id: string
  displayName: string
  color: string
}

export interface OrganizationSettingsPage {
  org: OrganizationSummary
  viewer: Viewer
  viewerRole: string
  members: OrganizationMemberSummary[]
  invitations: OrganizationInvitationSummary[]
  canManageMembers: boolean
  canManageOwners: boolean
  teams: OrganizationTeamSummary[]
  manageableCalendars: CalendarOptionSummary[]
}

export interface PublicProfilePage {
  username: string
  displayName: string
  avatarUrl: string | null
  isSelf: boolean
  calendars: CalendarSummary[]
  organizations: OrganizationSummary[]
  viewer: Viewer | null
}

export interface PublicCalendarPage {
  token: string
  calendar: CalendarSummary
  events: EventSummary[]
  viewer: Viewer | null
  following: boolean
  view: string
  date: string
  previousDate: string
  nextDate: string
  weekStart: string
  gridStart: string
  gridEnd: string
  label: string
  today: string
  now: string
  timeZone: string
  rssPath: string
}

export interface RegisterPage {
  viewer: Viewer | null
  registrationOpen: boolean
  emailVerificationPolicy: string
}

export interface RsvpPage {
  eventId: string
  token: string | null
  valid: boolean
  title: string | null
  whenText: string | null
  calendarName: string | null
  status: string | null
  requiresName: boolean
  viewer: Viewer | null
}

export interface ProviderSummary {
  id: string
  displayName: string
  enabled: boolean
  connectUrl: string
}

export interface ConnectionSummary {
  id: string
  provider: string
  providerName: string
  accountEmail: string | null
  displayName: string | null
  status: string
  lastSyncAt: string | null
  lastError: string | null
}

export interface SettingsPage {
  viewer: Viewer
  tab: string
  showHolidays: boolean
  holidayCatalog: HolidayCatalogItem[]
  subscribedHolidayIds: string[]
  customHolidays: CustomHolidaySummary[]
  providers: ProviderSummary[]
  connections: ConnectionSummary[]
}

export interface VerifyEmailPage {
  viewer: Viewer | null
  token: string | null
}

export interface RespondFriendRequestIn {
  id: string
}

export interface FriendsOut {
  friends: FriendSummary[]
  incoming: FriendRequestSummary[]
}

export interface RespondOrganizationInvitationIn {
  invitationId: string | null
  token: string | null
}

export interface OrganizationMembershipOut {
  organization: OrganizationSummary
  role: string
}

export interface AddOrganizationTeamMemberIn {
  teamId: string
  userId: string
}

export interface AdminCreateGroupIn {
  name: string
  storageQuotaBytes: number | null
}

export interface AdminDeleteCalendarIn {
  calendarId: string
}

export interface DeletedOut {
  ok: boolean
}

export interface AdminDeleteGroupIn {
  groupId: string
}

export interface AdminDeleteUserIn {
  userId: string
}

export interface AdminGroupMembersIn {
  groupId: string
}

export interface AdminGroupMemberSummary {
  userId: string
  username: string
  displayName: string
  admin: boolean
}

export interface AdminGroupMembersOut {
  groupId: string
  members: AdminGroupMemberSummary[]
}

export interface AdminGroupsIn {
}

export interface AdminGroupsOut {
  groups: GroupSummary[]
}

export interface AdminSetCalendarPublicIn {
  calendarId: string
  enabled: boolean
}

export interface AdminSetGroupMembersIn {
  groupId: string
  userIds: string[]
}

export interface AdminUpdateGroupIn {
  groupId: string
  name: string | null
  storageQuotaBytes: number | null
  clearQuota: boolean
}

export interface AdminUpdateUserIn {
  userId: string
  displayName: string | null
  email: string | null
  password: string | null
  admin: boolean | null
}

export interface CalendarAvailabilityIn {
  calendarId: string
}

export interface AvailabilityWindowIn {
  weekday: number
  startMinute: number
  endMinute: number
}

export interface CalendarAvailabilityOut {
  calendarId: string
  requestsEnabled: boolean
  slotMinutes: number
  accessMode: string
  effectiveAccessMode: string
  timeZone: string
  windows: AvailabilityWindowIn[]
}

export interface CalendarRequestsIn {
  calendarId: string
}

export interface TimeSlotRequestSummary {
  id: string
  calendarId: string
  calendarName: string
  requesterUserId: string | null
  requesterName: string | null
  requesterUsername: string | null
  requesterAvatarUrl: string | null
  requesterEmail: string | null
  start: string
  end: string
  message: string | null
  status: string
  createdAt: string
}

export interface CalendarRequestsOut {
  requests: TimeSlotRequestSummary[]
}

export interface CalendarSlotsIn {
  calendarId: string
  from: string
  to: string
}

export interface AvailabilitySlotOut {
  start: string
  end: string
  available: boolean
}

export interface AvailabilityDayOut {
  date: string
  slots: AvailabilitySlotOut[]
}

export interface CalendarSlotsOut {
  calendarId: string
  timeZone: string
  requestsEnabled: boolean
  days: AvailabilityDayOut[]
}

export interface ConnectProviderIn {
  providerId: string
  returnTo: string | null
}

export interface ConnectProviderOut {
  url: string
}

export interface CreateCalendarIn {
  displayName: string
  description: string | null
  timeZone: string | null
  color: string | null
  organizationId: string | null
}

export interface CreateCustomHolidayIn {
  title: string
  month: number
  day: number
}

export interface RecurrenceIn {
  frequency: string
  interval: number
  until: string | null
  count: number | null
}

export interface CreateEventIn {
  calendarId: string
  title: string
  description: string | null
  location: string | null
  url: string | null
  start: string
  end: string
  allDay: boolean
  timeZone: string | null
  recurrence: RecurrenceIn | null
}

export interface CreateOrganizationIn {
  slug: string
  displayName: string
  description: string | null
}

export interface CreateOrganizationTeamIn {
  organizationId: string
  slug: string
  name: string
  description: string | null
}

export interface DeleteCalendarIn {
  id: string
}

export interface DeleteCustomHolidayIn {
  id: string
}

export interface DeleteEventIn {
  id: string
  etag: string | null
}

export interface DeleteOrganizationIn {
  organizationId: string
}

export interface DeleteOrganizationTeamIn {
  teamId: string
}

export interface DisconnectAccountIn {
  connectionId: string
}

export interface DiscordGuildsIn {
  connectionId: string
}

export interface DiscordGuildSummary {
  id: string
  name: string
  iconUrl: string | null
  owner: boolean
  botPresent: boolean
  manageable: boolean
  inviteUrl: string | null
  imported: boolean
  externalCalendarId: string | null
  calendarId: string | null
  enabled: boolean
  lastSyncAt: string | null
  lastError: string | null
}

export interface DiscordGuildsOut {
  guilds: DiscordGuildSummary[]
}

export interface DiscordSyncSetupIn {
  connectionId: string
  guildId: string
}

export interface DiscordEventRouteSummary {
  id: string
  name: string
  start: string
  recurring: boolean
  calendarId: string | null
  skipped: boolean
}

export interface DiscordSyncSetupOut {
  defaultCalendarId: string | null
  calendars: CalendarOptionSummary[]
  events: DiscordEventRouteSummary[]
  imported: boolean
  enabled: boolean
  lastSyncAt: string | null
  lastError: string | null
}

export interface EventAttendeesIn {
  eventId: string
}

export interface EventAttendeeSummary {
  id: string
  userId: string | null
  username: string | null
  displayName: string | null
  avatarUrl: string | null
  email: string | null
  name: string | null
  status: string
}

export interface EventAttendeesOut {
  attendees: EventAttendeeSummary[]
  openRsvp: boolean
}

export interface GetEventRemindersIn {
  eventId: string
}

export interface EventRemindersOut {
  eventId: string
  offsetsSeconds: number[]
  useDefaults: boolean
  defaultOffsetsSeconds: number[]
  notifyAtStart: boolean
}

export interface FollowCalendarIn {
  token: string
}

export interface FollowOut {
  calendarId: string
  following: boolean
}

export interface FriendsIn {
}

export interface GetCalendarSharingIn {
  calendarId: string
}

export interface ShareSummary {
  userId: string
  username: string
  displayName: string
  permission: string
}

export interface CalendarSharingOut {
  shares: ShareSummary[]
  publicLinkEnabled: boolean
  publicLinkToken: string | null
  followerCount: number
  friends: FriendSummary[]
}

export interface GrantCalendarToTeamIn {
  calendarId: string
  teamId: string
  permission: string
}

export interface ImportDiscordGuildIn {
  connectionId: string
  guildId: string
}

export interface InviteToEventIn {
  eventId: string
  username: string
  name: string | null
}

export interface InviteToOrganizationIn {
  organizationId: string
  identifier: string
  role: string
}

export interface OrganizationInvitationOut {
  id: string
  status: string
}

export interface LoginIn {
  username: string
  password: string
}

export interface LoginOut {
  viewer: Viewer | null
  verificationRequired: boolean
  email: string | null
}

export interface LogoutIn {
}

export interface LogoutOut {
  ok: boolean
}

export interface MarkAllNotificationsReadIn {
}

export interface NotificationStateOut {
  unreadCount: number
}

export interface MarkNotificationReadIn {
  id: string
}

export interface MoveEventIn {
  id: string
  calendarId: string
  scope: string
  from: string | null
  etag: string | null
}

export interface MoveEventOut {
  events: EventSummary[]
}

export interface OrganizationInvitationsIn {
  organizationId: string
}

export interface OrganizationInvitationsOut {
  organizationId: string
  invitations: OrganizationInvitationSummary[]
}

export interface OrganizationMembersIn {
  organizationId: string
}

export interface OrganizationMembersOut {
  organizationId: string
  viewerRole: string | null
  canManageMembers: boolean
  canManageOwners: boolean
  members: OrganizationMemberSummary[]
}

export interface OrganizationTeamsIn {
  organizationId: string
}

export interface OrganizationTeamsOut {
  organizationId: string
  viewerRole: string | null
  canManageTeams: boolean
  teams: OrganizationTeamSummary[]
  manageableCalendars: CalendarOptionSummary[]
}

export interface OrganizationsIn {
}

export interface OrganizationsOut {
  organizations: OrganizationSummary[]
}

export interface PublicRequestTimeSlotIn {
  calendarToken: string
  name: string
  email: string | null
  start: string
  end: string
  message: string | null
}

export interface RequestTimeSlotOut {
  id: string
  status: string
}

export interface PublicRsvpIn {
  eventId: string
  name: string
  email: string | null
  status: string
}

export interface RsvpOut {
  status: string
}

export interface RegisterIn {
  username: string
  password: string
  email: string | null
}

export interface RegisterOut {
  viewer: Viewer | null
  verificationRequired: boolean
  email: string | null
}

export interface ReminderSettingsIn {
}

export interface ReminderSettingsOut {
  defaultOffsetsSeconds: number[]
  notifyAtStart: boolean
}

export interface RemoveDiscordImportIn {
  externalCalendarId: string
}

export interface RemoveEventAttendeeIn {
  eventId: string
  attendeeId: string
}

export interface RemoveFriendIn {
  userId: string
}

export interface RemoveOrganizationMemberIn {
  organizationId: string
  userId: string
}

export interface RemoveOrganizationTeamMemberIn {
  teamId: string
  userId: string
}

export interface RemoveShareIn {
  calendarId: string
  userId: string
}

export interface RequestTimeSlotIn {
  calendarId: string
  start: string
  end: string
  message: string | null
}

export interface ResendVerificationIn {
  username: string
}

export interface ResendVerificationOut {
  ok: boolean
}

export interface RespondEventInviteIn {
  eventId: string
  status: string
}

export interface RespondTimeSlotIn {
  id: string
  accept: boolean
  message: string | null
}

export interface RevokeCalendarFromTeamIn {
  calendarId: string
  teamId: string
}

export interface OrganizationInvitationIn {
  invitationId: string
  organizationId: string | null
}

export interface RotatePublicLinkIn {
  calendarId: string
}

export interface RsvpByTokenIn {
  token: string
  status: string
}

export interface DiscordEventRouteIn {
  eventId: string
  calendarId: string | null
  skipped: boolean
}

export interface SaveDiscordSyncIn {
  connectionId: string
  guildId: string
  defaultCalendarId: string | null
  routes: DiscordEventRouteIn[]
  enabled: boolean
}

export interface SearchUsersIn {
  query: string
}

export interface UserSearchResult {
  userId: string
  username: string
  displayName: string
  avatarUrl: string | null
  relationship: string
}

export interface UserSearchOut {
  results: UserSearchResult[]
}

export interface SendFriendRequestIn {
  username: string
}

export interface FriendRequestOut {
  status: string
  friend: FriendSummary | null
}

export interface SetCalendarHiddenIn {
  id: string
  hidden: boolean
}

export interface SetCalendarPublicIn {
  calendarId: string
  enabled: boolean
}

export interface SetDiscordImportEnabledIn {
  externalCalendarId: string
  enabled: boolean
}

export interface SetEmailVerificationIn {
  policy: string
}

export interface EmailVerificationPolicyOut {
  policy: string
}

export interface SetEventOpenRsvpIn {
  eventId: string
  enabled: boolean
}

export interface SetEventRemindersIn {
  eventId: string
  offsetsSeconds: number[]
  useDefaults: boolean
}

export interface SetOauthRegistrationIn {
  open: boolean
}

export interface SetOauthRegistrationOut {
  oauthRegistrationOpen: boolean
}

export interface SetOrganizationMemberRoleIn {
  organizationId: string
  userId: string
  role: string
}

export interface SetOrganizationTeamMemberRoleIn {
  teamId: string
  userId: string
  role: string
}

export interface SetPublicAccessIn {
  mode: string
}

export interface PublicAccessOut {
  mode: string
}

export interface SetRegistrationIn {
  open: boolean
}

export interface RegistrationOut {
  registrationOpen: boolean
}

export interface SetShowHolidaysIn {
  showHolidays: boolean
}

export interface HolidayStateOut {
  showHolidays: boolean
  subscribedIds: string[]
  customHolidays: CustomHolidaySummary[]
}

export interface SetUserPublicAccessIn {
  mode: string
}

export interface ShareCalendarIn {
  calendarId: string
  username: string
  permission: string
}

export interface SyncDiscordImportIn {
  externalCalendarId: string
}

export interface TransferCalendarIn {
  id: string
  organizationId: string | null
  teamId: string | null
}

export interface UnfollowCalendarIn {
  calendarId: string
}

export interface UpcomingRemindersIn {
  hours: number
}

export interface ReminderInstanceOut {
  eventId: string
  calendarId: string
  calendarName: string
  calendarColor: string
  title: string
  start: string
  allDay: boolean
  offsetSeconds: number
  remindAt: string
}

export interface UpdateCalendarIn {
  id: string
  displayName: string
  description: string | null
  timeZone: string
  color: string
}

export interface UpdateCalendarAvailabilityIn {
  calendarId: string
  requestsEnabled: boolean
  slotMinutes: number
  accessMode: string
  windows: AvailabilityWindowIn[]
}

export interface UpdateEventIn {
  id: string
  title: string | null
  description: string | null
  location: string | null
  url: string | null
  start: string | null
  end: string | null
  allDay: boolean | null
  recurrence: RecurrenceIn | null
  clearRecurrence: boolean
  etag: string | null
}

export interface UpdateHolidaySubscriptionsIn {
  subscribedIds: string[]
}

export interface UpdateOrganizationIn {
  organizationId: string
  displayName: string | null
  description: string | null
  visibility: string | null
}

export interface UpdateOrganizationTeamIn {
  teamId: string
  name: string | null
  description: string | null
}

export interface UpdateReminderSettingsIn {
  defaultOffsetsSeconds: number[]
  notifyAtStart: boolean
}

export interface UpdateSettingsIn {
  displayName: string
  timeZone: string
  accent: string
  email: string | null
  clearEmail: boolean
}

export interface UpdateShareIn {
  calendarId: string
  userId: string
  permission: string
}

export interface VerifyEmailIn {
  token: string
}

export interface VerifyEmailOut {
  ok: boolean
  email: string | null
}

export interface KalendeePages {
  "kalendee.admin": AdminPage
  "kalendee.directory": PublicDirectoryPage
  "kalendee.home": HomePage
  "kalendee.login": LoginPage
  "kalendee.notFound": NotFoundPage
  "kalendee.notifications": NotificationsPage
  "kalendee.org": OrganizationProfilePage
  "kalendee.orgSettings": OrganizationSettingsPage
  "kalendee.profile": PublicProfilePage
  "kalendee.publicCalendar": PublicCalendarPage
  "kalendee.register": RegisterPage
  "kalendee.rsvp": RsvpPage
  "kalendee.settings": SettingsPage
  "kalendee.verifyEmail": VerifyEmailPage
}

export type KalendeePageId = keyof KalendeePages

export interface KalendeeActions {
  "kalendee.acceptFriendRequest": { in: RespondFriendRequestIn; out: FriendsOut }
  "kalendee.acceptOrganizationInvitation": { in: RespondOrganizationInvitationIn; out: OrganizationMembershipOut }
  "kalendee.addOrganizationTeamMember": { in: AddOrganizationTeamMemberIn; out: OrganizationTeamMemberSummary }
  "kalendee.adminCreateGroup": { in: AdminCreateGroupIn; out: GroupSummary }
  "kalendee.adminDeleteCalendar": { in: AdminDeleteCalendarIn; out: DeletedOut }
  "kalendee.adminDeleteGroup": { in: AdminDeleteGroupIn; out: DeletedOut }
  "kalendee.adminDeleteUser": { in: AdminDeleteUserIn; out: DeletedOut }
  "kalendee.adminGroupMembers": { in: AdminGroupMembersIn; out: AdminGroupMembersOut }
  "kalendee.adminGroups": { in: AdminGroupsIn; out: AdminGroupsOut }
  "kalendee.adminSetCalendarPublic": { in: AdminSetCalendarPublicIn; out: AdminCalendarSummary }
  "kalendee.adminSetGroupMembers": { in: AdminSetGroupMembersIn; out: AdminGroupMembersOut }
  "kalendee.adminUpdateGroup": { in: AdminUpdateGroupIn; out: GroupSummary }
  "kalendee.adminUpdateUser": { in: AdminUpdateUserIn; out: AdminUserSummary }
  "kalendee.calendarAvailability": { in: CalendarAvailabilityIn; out: CalendarAvailabilityOut }
  "kalendee.calendarRequests": { in: CalendarRequestsIn; out: CalendarRequestsOut }
  "kalendee.calendarSlots": { in: CalendarSlotsIn; out: CalendarSlotsOut }
  "kalendee.connectProvider": { in: ConnectProviderIn; out: ConnectProviderOut }
  "kalendee.createCalendar": { in: CreateCalendarIn; out: CalendarSummary }
  "kalendee.createCustomHoliday": { in: CreateCustomHolidayIn; out: CustomHolidaySummary }
  "kalendee.createEvent": { in: CreateEventIn; out: EventSummary }
  "kalendee.createOrganization": { in: CreateOrganizationIn; out: OrganizationSummary }
  "kalendee.createOrganizationTeam": { in: CreateOrganizationTeamIn; out: OrganizationTeamSummary }
  "kalendee.declineFriendRequest": { in: RespondFriendRequestIn; out: FriendsOut }
  "kalendee.declineOrganizationInvitation": { in: RespondOrganizationInvitationIn; out: DeletedOut }
  "kalendee.deleteCalendar": { in: DeleteCalendarIn; out: DeletedOut }
  "kalendee.deleteCustomHoliday": { in: DeleteCustomHolidayIn; out: DeletedOut }
  "kalendee.deleteEvent": { in: DeleteEventIn; out: DeletedOut }
  "kalendee.deleteOrganization": { in: DeleteOrganizationIn; out: DeletedOut }
  "kalendee.deleteOrganizationTeam": { in: DeleteOrganizationTeamIn; out: DeletedOut }
  "kalendee.disconnectAccount": { in: DisconnectAccountIn; out: DeletedOut }
  "kalendee.discordGuilds": { in: DiscordGuildsIn; out: DiscordGuildsOut }
  "kalendee.discordSyncSetup": { in: DiscordSyncSetupIn; out: DiscordSyncSetupOut }
  "kalendee.eventAttendees": { in: EventAttendeesIn; out: EventAttendeesOut }
  "kalendee.eventReminders": { in: GetEventRemindersIn; out: EventRemindersOut }
  "kalendee.followCalendar": { in: FollowCalendarIn; out: FollowOut }
  "kalendee.friends": { in: FriendsIn; out: FriendsOut }
  "kalendee.getCalendarSharing": { in: GetCalendarSharingIn; out: CalendarSharingOut }
  "kalendee.grantCalendarToTeam": { in: GrantCalendarToTeamIn; out: OrganizationTeamCalendarSummary }
  "kalendee.importDiscordGuild": { in: ImportDiscordGuildIn; out: DiscordGuildSummary }
  "kalendee.inviteToEvent": { in: InviteToEventIn; out: EventAttendeesOut }
  "kalendee.inviteToOrganization": { in: InviteToOrganizationIn; out: OrganizationInvitationOut }
  "kalendee.login": { in: LoginIn; out: LoginOut }
  "kalendee.logout": { in: LogoutIn; out: LogoutOut }
  "kalendee.markAllNotificationsRead": { in: MarkAllNotificationsReadIn; out: NotificationStateOut }
  "kalendee.markNotificationRead": { in: MarkNotificationReadIn; out: NotificationStateOut }
  "kalendee.moveEvent": { in: MoveEventIn; out: MoveEventOut }
  "kalendee.organizationInvitations": { in: OrganizationInvitationsIn; out: OrganizationInvitationsOut }
  "kalendee.organizationMembers": { in: OrganizationMembersIn; out: OrganizationMembersOut }
  "kalendee.organizationTeams": { in: OrganizationTeamsIn; out: OrganizationTeamsOut }
  "kalendee.organizations": { in: OrganizationsIn; out: OrganizationsOut }
  "kalendee.publicRequestTimeSlot": { in: PublicRequestTimeSlotIn; out: RequestTimeSlotOut }
  "kalendee.publicRsvp": { in: PublicRsvpIn; out: RsvpOut }
  "kalendee.register": { in: RegisterIn; out: RegisterOut }
  "kalendee.reminderSettings": { in: ReminderSettingsIn; out: ReminderSettingsOut }
  "kalendee.removeDiscordImport": { in: RemoveDiscordImportIn; out: DeletedOut }
  "kalendee.removeEventAttendee": { in: RemoveEventAttendeeIn; out: EventAttendeesOut }
  "kalendee.removeFriend": { in: RemoveFriendIn; out: FriendsOut }
  "kalendee.removeOrganizationMember": { in: RemoveOrganizationMemberIn; out: DeletedOut }
  "kalendee.removeOrganizationTeamMember": { in: RemoveOrganizationTeamMemberIn; out: DeletedOut }
  "kalendee.removeShare": { in: RemoveShareIn; out: CalendarSharingOut }
  "kalendee.requestTimeSlot": { in: RequestTimeSlotIn; out: RequestTimeSlotOut }
  "kalendee.resendVerification": { in: ResendVerificationIn; out: ResendVerificationOut }
  "kalendee.respondEventInvite": { in: RespondEventInviteIn; out: RsvpOut }
  "kalendee.respondTimeSlot": { in: RespondTimeSlotIn; out: RequestTimeSlotOut }
  "kalendee.revokeCalendarFromTeam": { in: RevokeCalendarFromTeamIn; out: DeletedOut }
  "kalendee.revokeOrganizationInvitation": { in: OrganizationInvitationIn; out: OrganizationInvitationOut }
  "kalendee.rotatePublicLink": { in: RotatePublicLinkIn; out: CalendarSharingOut }
  "kalendee.rsvpByToken": { in: RsvpByTokenIn; out: RsvpOut }
  "kalendee.saveDiscordSync": { in: SaveDiscordSyncIn; out: DiscordGuildSummary }
  "kalendee.searchUsers": { in: SearchUsersIn; out: UserSearchOut }
  "kalendee.sendFriendRequest": { in: SendFriendRequestIn; out: FriendRequestOut }
  "kalendee.setCalendarHidden": { in: SetCalendarHiddenIn; out: CalendarSummary }
  "kalendee.setCalendarPublic": { in: SetCalendarPublicIn; out: CalendarSharingOut }
  "kalendee.setDiscordImportEnabled": { in: SetDiscordImportEnabledIn; out: DiscordGuildSummary }
  "kalendee.setEmailVerification": { in: SetEmailVerificationIn; out: EmailVerificationPolicyOut }
  "kalendee.setEventOpenRsvp": { in: SetEventOpenRsvpIn; out: EventSummary }
  "kalendee.setEventReminders": { in: SetEventRemindersIn; out: EventRemindersOut }
  "kalendee.setOauthRegistration": { in: SetOauthRegistrationIn; out: SetOauthRegistrationOut }
  "kalendee.setOrganizationMemberRole": { in: SetOrganizationMemberRoleIn; out: OrganizationMemberSummary }
  "kalendee.setOrganizationTeamMemberRole": { in: SetOrganizationTeamMemberRoleIn; out: OrganizationTeamMemberSummary }
  "kalendee.setPublicAccess": { in: SetPublicAccessIn; out: PublicAccessOut }
  "kalendee.setRegistration": { in: SetRegistrationIn; out: RegistrationOut }
  "kalendee.setShowHolidays": { in: SetShowHolidaysIn; out: HolidayStateOut }
  "kalendee.setUserPublicAccess": { in: SetUserPublicAccessIn; out: Viewer }
  "kalendee.shareCalendar": { in: ShareCalendarIn; out: CalendarSharingOut }
  "kalendee.syncDiscordImport": { in: SyncDiscordImportIn; out: DiscordGuildSummary }
  "kalendee.transferCalendar": { in: TransferCalendarIn; out: CalendarSummary }
  "kalendee.unfollowCalendar": { in: UnfollowCalendarIn; out: FollowOut }
  "kalendee.upcomingReminders": { in: UpcomingRemindersIn; out: ReminderInstanceOut[] }
  "kalendee.updateCalendar": { in: UpdateCalendarIn; out: CalendarSummary }
  "kalendee.updateCalendarAvailability": { in: UpdateCalendarAvailabilityIn; out: CalendarAvailabilityOut }
  "kalendee.updateEvent": { in: UpdateEventIn; out: EventSummary }
  "kalendee.updateHolidaySubscriptions": { in: UpdateHolidaySubscriptionsIn; out: HolidayStateOut }
  "kalendee.updateOrganization": { in: UpdateOrganizationIn; out: OrganizationSummary }
  "kalendee.updateOrganizationTeam": { in: UpdateOrganizationTeamIn; out: OrganizationTeamSummary }
  "kalendee.updateReminderSettings": { in: UpdateReminderSettingsIn; out: ReminderSettingsOut }
  "kalendee.updateSettings": { in: UpdateSettingsIn; out: Viewer }
  "kalendee.updateShare": { in: UpdateShareIn; out: CalendarSharingOut }
  "kalendee.verifyEmail": { in: VerifyEmailIn; out: VerifyEmailOut }
}

export type KalendeeActionId = keyof KalendeeActions
